# General SEO settings.
title: Aviem Zur
description: "Aviem Zur's personal homepage"
url: http://aviemzur.com
baseurl: ""
favicon: /images/favicon.ico

# Author settings.
author:
  name      : Aviem Zur
  job       : Data Architect @ Natural Intelligence; Committer & PMC Member, Apache Beam; Committer & PPMC Member, Apache Liminal (Incubating)
  bio       : Data Architect at <a href="https://www.naturalint.com/">Natural Intelligence</a>, working on big data frameworks and platforms. Committer and PMC member in the <a href="https://beam.apache.org">Apache Beam</a> project. Committer and PPMC member in the <a href="https://liminal.apache.org">Apache Liminal (Incubating)</a> project.
  thumb     : /images/aviemzur.png
  github    : https://github.com/aviemzur
  twitter   : https://twitter.com/aviemzur
  linkedin  : https://www.linkedin.com/in/aviemzur

# Specify source location.
sass:
  sass_dir: _scss
  style: compressed # expanded
exclude:
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Build settings.
permalink: /blog/:year/:title/
paginate: 3
paginate_path: "/blog/page/:num/"
gems:
  - jekyll-paginate
comments: true

markdown: kramdown
highlighter: rouge

# GitHub pages.
repository: aviemzur/aviemzur.github.io

# Menu.
navbar:
  - slug: blog
    title: Blog
