# General SEO settings.
title: Aviem Zur
description: "Aviem Zur's personal homepage"
url: http://aviemzur.com
baseurl: ""
favicon: /images/favicon.ico

# Author settings.
author:
  name      : Aviem Zur
  job       : Software Engineer at PayPal; Committer, Apache Beam
  bio       : Working as a Software Engineer at PayPal and a committer in the <a href="https://beam.apache.org">Apache Beam</a> team.
  thumb     : /images/aviemzur.jpeg
  github    : https://github.com/aviemzur
  twitter   : https://twitter.com/aviemzur
  linkedin  : https://www.linkedin.com/in/aviemzur

# Specify source location.
sass:
  sass_dir: _scss
  style: compressed # expanded
exclude:
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Build settings.
permalink: /blog/:year/:title/
paginate: 3
paginate_path: "/blog/page/:num/"
gems:
  - jekyll-paginate
comments: true

markdown: kramdown
highlighter: rouge

# GitHub pages.
repository: aviemzur/aviemzur.github.io

# Menu.
navbar:
  - slug: blog
    title: Blog
